name: Build

on:
    push:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        permissions:
            contents: 'read'
            id-token: 'write'

        steps:
            -   uses: actions/checkout@v4

            -   name: Set up JDK 21
                uses: actions/setup-java@v4
                with:
                    java-version: '21'
                    distribution: 'adopt'

            -   name: Cache local Maven repository
                uses: actions/cache@v4
                with:
                    path: ~/.m2/repository
                    key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                    restore-keys: |
                        ${{ runner.os }}-maven-

            -   name: Maven Build Hilla
                run: mvn -f hilla/pom.xml -B test

            -   name: Maven Build Thymeleaf
                run: mvn -f thymeleaf/pom.xml -B test

            -   name: Maven Build Vaadin
                run: mvn -f vaadin/pom.xml -B test
